name: Install Python Dependencies
description: Setup venv and install packages

runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Clone python-greetings
      shell: cmd
      run: |
        git clone https://github.com/mtararujs/python-greetings.git python-greetings

    - name: Install dependencies
      shell: cmd
      working-directory: python-greetings
      run: |
        echo "Installing dependencies..."
        python -m venv venv
        venv\Scripts\python -m pip install -r requirements.txt