name: Deploy Service
description: Deploys the python-greetings application to a specified environment

inputs:
  env:
    required: true
  port:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v4

    - name: Clone python-greetings
      shell: cmd
      run: |
        git clone https://github.com/mtararujs/python-greetings.git python-greetings

    - name: Deploy
      shell: cmd
      working-directory: python-greetings
      run: |
        echo "Deploying to ${{ inputs.env }}..."

        pm2 delete greetings-app-${{ inputs.env }} & exit /B 0

        pm2 start app.py \
          --name greetings-app-${{ inputs.env }} \
          --interpreter venv\Scripts\python.exe \
          -- --port=${{ inputs.port }}