name: Test Pipeline

on:
  push:
    branches: [ main ]

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings
        uses: ./.github/actions/install-deps

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          env: dev
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/test
        with:
          env: dev

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          env: dev
          port: 7002

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/test
        with:
          env: dev

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          env: dev
          port: 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/test
        with:
          env: dev

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          env: dev
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/test
        with:
          env: dev